// phrases.js
const phrases = [
  "May the Force be with you",
  "I am Groot",
  "Wakanda forever",
  "I'm Batman",
  "Bazinga!",
  "Winter is coming",
  "I solemnly swear I am up to no good",
  "Expecto Patronum",
  "You shall not pass!",
  "Why so serious?",
  "To infinity and beyond!",
  "Here’s Johnny!",
  "I volunteer as tribute",
  "Hakuna Matata",
  "Just keep swimming",
  "I am inevitable",
  "I drink and I know things",
  "I love the smell of napalm in the morning",
  "Say hello to my little friend",
  "It's a trap!",
  "I see dead people",
  "With great power comes great responsibility",
  "Life finds a way",
  "I am Iron Man",
  "You can’t handle the truth!",
  "Hasta la vista, baby",
  "Yippee-ki-yay",
  "I am your father",
  "I'm the king of the world!",
  "Houston, we have a problem",
  "I am Spartacus!",
  "Avengers, assemble!",
  "This is the way",
  "I am the danger",
  "One ring to rule them all",
  "By Grabthar's hammer!",
  "I’m not a cat",
  "You know nothing, Jon Snow",
  "Cowabunga!",
  "Oh, hi Mark",
  "I’m Mary Poppins, y’all",
  "I’ve got a bad feeling about this",
  "We’re all mad here",
  "It’s morphin’ time!",
  "Clear eyes, full hearts, can’t lose",
  "I am the law!",
  "I am Groot",
  "I’m pickin’ up good vibrations",
  "Don’t stop believin’",
  "Why are you running?",
  "Say my name",
  "I’m the one who knocks",
  "I drink your milkshake!",
  "I see dead people",
  "Game over, man!",
  "I’m on a boat",
  "Who you gonna call?",
  "I’ll be back",
  "It’s clobberin’ time!",
  "This is fine",
  "One does not simply walk into Mordor",
  "We have a Hulk",
  "I’m Rick James, b****",
  "I am inevitable",
  "I am vengeance",
  "Don’t make me angry",
  "I am Iron Man",
  "Why so serious?",
  "I have spoken",
  "I am the Senate",
  "I’m the captain now",
  "You shall not pass",
  "Winter is coming",
  "I’m king of the world!",
  "I see dead people",
  "I volunteer as tribute",
  "Wubba Lubba Dub Dub!",
  "I am Groot",
  "Live long and prosper",
  "You can’t handle the truth!",
  "I love lamp",
  "I am the one who knocks",
  "To infinity and beyond",
  "I drink and I know things",
  "Bazinga!",
  "I am your father",
  "I have the high ground",
  "I am inevitable",
  "I am Batman",
  "I am the danger",
  "I am vengeance",
  "I am Iron Man",
  "I see dead people",
  "It’s a trap!",
  "I’m too old for this sh*t",
  "You’re tearing me apart, Lisa!",
  "I am the law",
  "I am the Senate",
  "This is the way",
  "I love the smell of napalm in the morning",
  "I am Spartacus",
  "Avengers, assemble",
  "I’m your huckleberry",
  "Houston, we have a problem",
  "I’m walking here!",
  "I am Groot",
  "I volunteer as tribute",
  "Hakuna Matata",
  "Just keep swimming",
  "I am inevitable",
  "I drink and I know things",
  "Wakanda forever",
  "May the Force be with you",
  "I’m Batman",
  "Hi joel, I hope you give me 10000000 roblo"
];

